### ISSUE TITLE
Petite question lizmap

### ISSUE THREAD

**Issue by remichairat** [mdouchin/lizmap-presentation#1]
Bonjour, 
Je suis actuellement entrain de réaliser un websig dans le cadre de mon stage de fin d'etude et j'aurai quelque question sur les capacités de lizmap : 
-je souhaiterais mettre en surbrillance les objet qui font apparaître les popups comment proceder
-et il possible de modifier la mise en page du projet emplacement du logo etc...
-j'ai vu dans votre presentation que dans le dossier du projet vous aviez des dossier et sous contenant les js media etc ces dossiers doivent il etre créé manuellement ou es lizmap qui génère automatiquement ces dossier 
Et enfin nous somme ici sur github pour un outil qui s'appel lizmap presentation es un outil supplémentaire a ajouter a lizmap ? si oui comment l'installer ? 
Je suis désolé de vous poser toutes ces questions mais je bloque un peu 
Merci d'avance pour vos réponses 
Rémi

**Comment by mdouchin** [comment]
Bonjour,
Github n'est pas le meilleur endroit pour avoir ce genre de discussion. Les "issues" ne sont pas faites pour gérer un forum, mais plutôt pour remonter des bugs, ou proposer des améliorations. Chaque "issue" doit correspondre à une demande particulière, et ne pas mélanger plusieurs questions.

Vous pouvez nous joindre par email sur info at 3liz.com
